import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/app/globals.css";
import { Toaster } from "sonner";

const yekan = localFont({
  src: "./fonts/Yekan.woff2",
  variable: "--font-yekan",
  display: "swap",
});

export const metadata: Metadata = {
  title: "سامانه مزایده ها",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${yekan.variable} antialiased `}>
      <body className="font-yekan h-full" cz-shortcut-listen="true">
        <Toaster
          className="font-yekan rtl flex gap-x-3"
          richColors
          position="top-left"
          // theme={`${theme === "dark" ? "dark" : "light"}`}
          // duration={500000}
        />
        {children}
      </body>
    </html>
  );
}
